version: "3.9"

services:

  telegram-scraper:
    build: ./telegram-scraper
    container_name: telegram-scraper
    volumes:
      - leak_files:/files
      - telegram_session:/session_storage
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_PHONE: ${TELEGRAM_PHONE}

      # VALID TELEGRAM CHANNELS ONLY (comma-separated)
      TARGET_CHANNELS: "universecloudtxt,https://t.me/+d3feCXKJGYE4MDgy,https://t.me/+U843WkgFogBjZDI1"

      # scraper -> extractor
      FORWARD_URL: "http://extractor-engine:8001/extract"
    restart: unless-stopped


  extractor-engine:
    build: ./extractor-engine
    container_name: extractor-engine
    volumes:
      - leak_files:/files
    environment:
      MAX_READ_BYTES: 5000000
    ports:
      - "8001:8001"
    restart: unless-stopped


  filter-engine:
    build: ./filter-engine
    container_name: filter-engine
    environment:
      SCOPE_DOMAIN: "squ.edu.om"
      SCOPE_EMAIL: "@squ.edu.om"
      N8N_WEBHOOK: ${N8N_WEBHOOK}
    ports:
      - "7000:7000"
    restart: unless-stopped

volumes:
  leak_files:
  telegram_session:
